---
- name: remove postgresql package
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - postgresql-server 
    - postgresql-contrib


- name: removed dependencies for pip modules
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - gcc
      - python-devel
      - postgresql-devel
