---
- name: remove postgress package
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - postgresql12-server 
    - postgresql12


- name: removed dependencies for pip modules
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - gcc
      - python-devel
      - postgresql-devel
