---
#- hosts: maquina1
#  gather_facts: yes  
#  become: true
#  become_method: "sudo"
#  vars:
#    postgres_server_initdb_become: true
#    postgres_server_user: root
#    dbs:
#    - { db_name: "artifactory", db_owner: "artifactory" }
#    - { db_name: "xraydb", db_owner: "xray" }
#    db_users:
#    - { db_user: "artifactory", db_password: "artifactory" }
#    - { db_user: "xray", db_password: "xray" }
#  roles:
#    - {role: 'postgres', tags: 'postgres-role'}

- hosts: maquina1
  gather_facts: yes  
  become: true
  become_method: "sudo"
  vars:
    local_artifactory_tar: "/opt/project/repositories-ansible-azure/jfrog-artifactory-pro-6.23.1.zip"
    master_key: "c97b862469de0d94fbb7d48130637a5a"
    join_key: "9bcca98f375c0728d907cc6ee39d4f02"
    db_download_url: "https://jdbc.postgresql.org/download/postgresql-42.2.12.jar"
    db_type: "postgresql"
    db_driver: "org.postgresql.Driver"
    db_url: "jdbc:postgresql://192.168.30.21:5432/artifactory"
    db_user: "artifactory"
    db_password: "Art1fAct0ry"
    server_name: "192.168.30.22"
  roles:
    - {role: 'artifactory-small', tags: 'artifactory-role'}

- hosts: maquina2
  gather_facts: yes  
  become: true
  become_method: "sudo"
  vars:
    local_xray_tar: "/opt/project/repositories-ansible-azure/xray-centos-2.9.0.tar.gz"
    jfrog_url: "192.168.30.22"
    master_key: "c97b862469de0d94fbb7d48130637a5a"
    join_key: "9bcca98f375c0728d907cc6ee39d4f02"
    db_type: "postgresql"
    db_driver: "org.postgresql.Driver"
    db_url: "postgres://192.168.30.21:5432/xraydb?sslmode=disable"
    db_user: "xray"
    db_password: "xray"
  roles:
    - {role: 'xray-small', tags: 'xray-role'}

