---
#install
#remove
action_execute: install

ntp_daemon: "chronyd"
ntp_cron_daemon: "crond"

ntp_package: "chrony"
ntp_timezone: "America/Lima"
ntp_config_file: "/etc/chrony.conf"



#ntp_driftfile: "/var/lib/ntp/drift"
ntp_driftfile: "/var/lib/chrony/drift"
ntp_tinker_panic: true
ntp_area: 'centos'
ntp_servers:
  - "0{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
  - "1{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
  - "2{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
  - "3{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
ntp_restrict:
  - "127.0.0.1"
  - "::1"
