---
- name: Ensure {{ ntp_package }} package is installed.
  package:
    name: "{{ ntp_package }}"
    state: present

- name: Set timezone to {{ ntp_timezone }}
  timezone:
    name: "{{ ntp_timezone }}"
  notify: restart cron

- name: Generate ntp configuration file {{ ntp_config_file }}
  template:
    src: "{{ ntp_config_file | basename }}.j2"
    dest: "{{ ntp_config_file }}"
    mode: 0644
  notify: restart ntp

- name: Ensure {{ ntp_daemon }} is running and enabled as configured.
  service:
    name: "{{ ntp_daemon }}"
    state: started
    enabled: true

