---
- name: remove postgress package
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - postgresql96-server 
    - postgresql96
    - postgresql96-contrib
    - postgresql96-libs

- name: remove postgresql old package
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - postgresql-server 
    - postgresql
    - postgresql-libs
    - postgresql-contrib
  ignore_errors: true

- name: removed dependencies for pip modules
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - gcc
      - python-devel
      - postgresql-devel
