---


#Error Messages: [This JIRA cluster has other active nodes. Please shutdown other active nodes, You are currently attached to node 'red-#node-3'. Nodes 'red-node-1' are also active., It may take up to five minutes for shutdown nodes to be removed from the cluster.]

#both node in jira can be configured at the same time

- name: ensure java is installed
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - java-1.8.0-openjdk
      - java-1.8.0-openjdk-devel


- name: copy confluence bin 
  copy:
    src: "{{ role_path }}/files/atlassian-confluence-6.7.2-x64.bin"
    dest: "/home/atlassian-confluence-6.7.2-x64.bin"
    mode: '0755'

- name: copy confluence custom bin 
  copy:
    src: "{{ role_path }}/files/atlassian-confluence-6.13.15.tar.gz"
    dest: "/home/atlassian-confluence-6.13.15.tar.gz"
    mode: '0755'



- name: Disable SELinux
  selinux:
    state: disabled

- name: Disable SELinux temporaly
  shell: "setenforce 0"
  ignore_errors: true

#https://confluence.atlassian.com/bitbucketserver/running-the-bitbucket-server-installer-776640183.html

#https://github.com/Praqma/jira/blob/master/jira-response.varfile

#https://github.com/Praqma/confluence/blob/master/confluence-response.varfile

- name: copy response.varfile template to server
  template:
    src: "{{ role_path }}/templates/response.varfile.j2"
    dest: "/home/response.varfile"

- name: install confluence server
  command: "/home/atlassian-confluence-6.7.2-x64.bin -q -varfile /home/response.varfile"
  register: install_results
  ignore_errors: true

- name: view install results
  debug:
    var: install_results

- name: make sure confluence is responding on configure port
  wait_for: port=8090 delay=3 timeout=300

- name: ensure dependencies for pip modules are installed
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - gcc
      - python-devel

- name: ensure epel is installed
  yum:
    name: epel-release
    state: present

- name: ensure python-pip is installed
  yum:
    name: python-pip
    state: present

- name: ensure python-wheel is installed
  yum:
    name: python-wheel
    state: present

- name: Make sure  setuptools is installed
  pip:
    name: setuptools
    state: present

- name: Make sure  mechanize is installed
  pip:
    name: mechanize
    state: present

#https://bitbucket.newverveconsulting.com/projects/PUB/repos/auto_atlassian_setup/browse/auto-jira-setup.py
#https://bitbucket.newverveconsulting.com/projects/PUB/repos/auto_atlassian_setup/browse/auto-confluence-setup.py


- name: copy setup template to server
  template:
    src: "{{ role_path }}/templates/setup.py.j2"
    dest: "/home/setup.py"
    mode: "755"

#- name : start python setup for confluence
#  shell: python /home/setup.py
