---

- name: Get running processes
  shell: "ps -ef | grep -v grep | grep confluence | awk '{print $2}'"
  register: running_processes

- name: Kill running processes
  shell: "kill {{ item }}"
  with_items: "{{ running_processes.stdout_lines }}"


- name : stop service confluence
  systemd:
    state: stopped
    enabled: no
    name: confluence

- name:  remove directory {{confluence_home_path}}
  file:
    path: " {{confluence_home_path}}"
    state: absent

- name:  remove directory {{confluence_install_path}}
  file:
    path: "{{confluence_install_path}}"
    state: absent

- name:  remove directory /opt/confluence
  file:
    path: "/opt/confluence"
    state: absent
