---


#Error Messages: [This JIRA cluster has other active nodes. Please shutdown other active nodes, You are currently attached to node 'red-#node-3'. Nodes 'red-node-1' are also active., It may take up to five minutes for shutdown nodes to be removed from the cluster.]

#both node in jira can be configured at the same time

- name: ensure java is installed
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - java-1.8.0-openjdk
      - java-1.8.0-openjdk-devel


- name: copy jira bin 
  copy:
    src: "{{ role_path }}/files/atlassian-jira-software-7.8.0-x64.bin"
    dest: "/home/atlassian-jira-software-7.8.0-x64.bin"
    mode: '0755'

- name: copy jira custom bin 
  copy:
    src: "{{ role_path }}/files/atlassian-jira-software-7.13.17.tar.gz"
    dest: "/home/atlassian-jira-software-7.13.17.tar.gz"
    mode: '0755'

- name: copy postgresql custom jar  
  copy:
    src: "{{ role_path }}/files/postgresql-42.2.16.jar"
    dest: "/home/postgresql-42.2.16.jar"
    mode: '0755'

- name: Disable SELinux
  selinux:
    state: disabled

- name: Disable SELinux temporaly
  shell: "setenforce 0"

#https://confluence.atlassian.com/bitbucketserver/running-the-bitbucket-server-installer-776640183.html

#https://github.com/Praqma/jira/blob/master/jira-response.varfile

- name: copy response.varfile template to server
  template:
    src: "{{ role_path }}/templates/response.varfile.j2"
    dest: "/home/response.varfile"

- name: install jira server
  shell: "/home/atlassian-jira-software-7.8.0-x64.bin -q -varfile /home/response.varfile"
  register: install_results
  ignore_errors: true

- name: view install results
  debug:
    var: install_results

- name: make sure jira is responding on configure port
  wait_for: port=8080 delay=3 timeout=300

- name : stop service jira
  service:
    state: stopped
    name: jira

- name: pause for 1 minute
  pause: 
    minutes: 1

- name: copy dbconfig template to server
  template:
    src: "{{ role_path }}/templates/dbconfig.xml.j2"
    dest: "{{jira_home_path}}/dbconfig.xml"
    owner: jira
    group: jira

- name: copy cluster template to server
  template:
    src: "{{ role_path }}/templates/cluster.properties.j2"
    dest: "{{jira_home_path}}/cluster.properties"
    owner: jira
    group: jira

- name: Get running processes
  shell: "ps -ef | grep -v grep | grep jira | awk '{print $2}'"
  register: running_processes

- name: Kill running processes
  shell: "kill {{ item }}"
  with_items: "{{ running_processes.stdout_lines }}"

- name: pause for 1 minute
  pause: 
    minutes: 1

- name : start service jira
  shell: service jira start

- name: make sure jira is responding on configure port
  wait_for: port=8080 delay=3 timeout=300

- name: ensure dependencies for pip modules are installed
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - gcc
      - python-devel

- name: ensure epel is installed
  yum:
    name: epel-release
    state: present

- name: ensure python-pip is installed
  yum:
    name: python-pip
    state: present

- name: ensure python-wheel is installed
  yum:
    name: python-wheel
    state: present

- name: Make sure  setuptools is installed
  pip:
    name: setuptools
    state: present

- name: Make sure  mechanize is installed
  pip:
    name: mechanize
    state: present

#https://bitbucket.newverveconsulting.com/projects/PUB/repos/auto_atlassian_setup/browse/auto-jira-setup.py
#

- name: copy setup template to server
  template:
    src: "{{ role_path }}/templates/setup.py.j2"
    dest: "/home/setup.py"
    mode: "755"

- name : start python setup for jira
  shell: python /home/setup.py

