---

- name: Get running processes
  shell: "ps -ef | grep -v grep | grep jira | awk '{print $2}'"
  register: running_processes

- name: Kill running processes
  shell: "kill {{ item }}"
  with_items: "{{ running_processes.stdout_lines }}"


- name : stop service jira
  systemd:
    state: stopped
    enabled: no
    name: jira

- name:  remove directory {{jira_home_path}}
  file:
    path: " {{jira_home_path}}"
    state: absent

- name:  remove directory {{jira_install_path}}
  file:
    path: "{{jira_install_path}}"
    state: absent

- name:  remove directory /opt/jira
  file:
    path: "/opt/jira"
    state: absent

