---
- name: copy bitbucket bin 
  copy:
    src: "{{ role_path }}/files/atlassian-bitbucket-5.8.0-linux-x64.bin"
    dest: "/home/atlassian-bitbucket-5.8.0-linux-x64.bin"
    mode: '0755'

- name: Import a key from a url
  rpm_key:
    state: present
    key: http://opensource.wandisco.com/RPM-GPG-KEY-WANdisco

- name: Add WAN disco repo
  yum_repository:
    name: wandisco-git
    description: WANdisco Distribution of git
    file: wandisco-git
    baseurl: http://opensource.wandisco.com/rhel/$releasever/git/$basearch
    gpgcheck: yes
    enabled: yes
    gpgkey: http://opensource.wandisco.com/RPM-GPG-KEY-WANdisco

- name: install git
  yum: 
    name:  "git"
    state: present
    disablerepo: "*"
    enablerepo: "wandisco-git,base"


#- name: ensure dependencies for pip modules are installed
#  yum:
#    name: "{{ packages }}"
#    state: present
#  vars:
#    packages:
#      - gcc
#      - python-devel

#- name: ensure epel is installed
#  yum:
#    name: epel-release
#    state: present

#- name: ensure python-pip is installed
#  yum:
#    name: python-pip
#    state: present

#- name: ensure python-wheel is installed
#  yum:
#    name: python-wheel
#    state: present

#- name: Make sure  setuptools is installed
#  pip:
#    name: setuptools
#    state: present

#- name: Make sure  mechanize is installed
#  pip:
#    name: mechanize
#    state: present

#https://github.com/Praqma/bitbucket/blob/master/bitbucket-response.varfile
#https://confluence.atlassian.com/bitbucketserver/running-the-bitbucket-server-installer-776640183.html
- name: copy response.varfile template to server
  template:
    src: "{{ role_path }}/templates/response.varfile.j2"
    dest: "/home/response.varfile"

- name: install bitbucket server
  shell: "/home/atlassian-bitbucket-5.8.0-linux-x64.bin -q -varfile /home/response.varfile"
  register: install_results
  ignore_errors: true

- name: view install results
  debug:
    var: install_results

- name : stop service atlbitbucket
  systemd:
    state: stopped
    enabled: yes
    name: atlbitbucket

- name: stop bitbucket services
  shell: "{{bitbucket_install_path}}/bin/stop-bitbucket.sh --no-search "

- name: Recursively change ownership of a directory {{bitbucket_home_path}}/shared/ 
  file:
    path: "{{bitbucket_home_path}}/shared"
    state: directory
    recurse: yes
    owner: atlbitbucket
    group: atlbitbucket


- name:  create directory /home/atlbitbucket
  file:
    path: "/home/atlbitbucket"
    state: directory

#https://confluence.atlassian.com/bitbucketserver/adding-and-removing-data-center-nodes-776640178.html
#add a name to the cluster node


- name: Print all relevant facts for hostname asignation in bitbucket
  debug:
    var: ansible_hostname

- name: configure clustername for the bitbucket node
  lineinfile: 
    dest: "{{bitbucket_install_path}}/bin/_start-webapp.sh"
    regexp: "^#JVM_SUPPORT_RECOMMENDED_ARGS=" 
    line: 'JVM_SUPPORT_RECOMMENDED_ARGS=-Dcluster.node.name={{ansible_hostname}}' 
    create: yes



#https://confluence.atlassian.com/bitbucketserver/bitbucket-server-config-properties-776640155.html
#https://confluence.atlassian.com/bitbucketserver/how-to-install-and-configure-a-remote-elasticsearch-instance-815577748.html
#shared folder of your homepath
 
- name: Print all relevant facts for ip asignation in butbucket
  debug:
    var: ansible_eth1.ipv4.address

- name: copy bitbucket.properties template to server
  template:
    src: "{{ role_path }}/templates/bitbucket.properties.j2"
    dest: "{{bitbucket_home_path}}/shared/bitbucket.properties"
    owner: atlbitbucket
    group: atlbitbucket
    mode: '0666'


- name: copy bitbucket.service template to server
  template:
    src: "{{ role_path }}/templates/bitbucket.service.j2"
    dest: "/etc/systemd/system/bitbucket.service"
    owner: root
    group: root
    mode: '0755'

- name: copy ulimit template to server
  template:
    src: "{{ role_path }}/templates/ulimit.j2"
    dest: "/etc/security/limits.conf"
    owner: root
    group: root
    mode: '0644'

 
- name : start service atlbitbucket
  systemd:
    state: started
    enabled: yes
    name: bitbucket



