---
#https://confluence.atlassian.com/bitbucketserver/supported-platforms-776640981.html
#must be postgress-9.5 to 12

- name: Install the postgress rpm from a remote repo
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: install postgress-12 package
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - postgresql12-server 
    - postgresql12

- name: execute setup for db 
  shell: /usr/pgsql-12/bin/postgresql-12-setup initdb
  register: output
  ignore_errors: yes

- name: view result for setup
  debug: 
    msg: "{{output.stdout}}"

- name : start systemctl postgres-12
  systemd:
    state: started
    enabled: yes
    name: postgresql-12

- name: ensure dependencies for pip modules are installed
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - gcc
      - python-devel
      - postgresql-devel

- name: ensure epel is installed
  yum:
    name: epel-release
    state: present

- name: ensure python-pip is installed
  yum:
    name: python-pip
    state: present

- name: ensure python-wheel is installed
  yum:
    name: python-wheel
    state: present

- name: Make sure  setuptools is installed
  pip:
    name: setuptools
    state: present

- name: Make sure psycopg2 is installed
  pip:
    name: psycopg2
    state: present

- name: "Create a new database with name {{database_name}}"
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{database_name}}"
    encoding: UNICODE
    lc_collate: C
    lc_ctype: C
    template: template0
    ssl_mode: require

- name: "Create a new username with name {{database_user}}"
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{database_user}}"
    password: "{{database_pass}}"
    ssl_mode: require

- name: "assign permission to {{database_user}} in {{database_name}}"
  become: yes
  become_user: postgres
  postgresql_privs:
    db: postgres
    state: present
    privs: ALL
    type: database
    obj: "{{database_name}}"
    role: "{{database_user}}"
    ssl_mode: require

- name: configure to allow listen to multiple adress
  lineinfile: 
    dest: /var/lib/pgsql/12/data/postgresql.conf
    regexp: "^listen_addresses=" 
    line: "listen_addresses='*'" 
    create: yes
  notify: 
  - daemon_reload
  - restart_postgresql

- name: configure to allow network to connect to this server
  lineinfile: 
    dest: /var/lib/pgsql/12/data/pg_hba.conf
    regexp: "^host all all 192.168.30.0/24 trust" 
    line: "host all all 192.168.30.0/24 trust" 
    create: yes
  notify: 
  - daemon_reload
  - restart_postgresql

#sudo su - postgres
#/usr/pgsql-12/bin/psql
#command to check
#\l for list database
#\du for list user
#\q to quit
