---
#install
#remove
action_execute: install

bitbucket_home_path: "/opt/atlassian/home"
bitbucket_install_path: "/opt/atlassian/install"


#curl -s 'http://192.168.30.22:9200/' -u usuariobuckler:p@ssw0rd
elastic_search_ip: "http://192.168.30.22:9200/"
elastic_search_user: "usuariobuckler"
elastic_search_pass: "p@ssw0rd"

clustering_group: "Devops"
clustering_group_pass: "p@ssw0rd"

first_node: "192.168.30.21"
second_node: "192.168.30.23"
load_balancer_ip: "192.168.30.22"
#https://confluence.atlassian.com/bitbucketserver/bitbucket-server-config-properties-776640155.html
#https://confluence.atlassian.com/bitbucketserver/how-to-install-and-configure-a-remote-elasticsearch-instance-815577748.html

admin_user: "bitbucketlocal"
admin_pass: "password"
admin_email: "bitbucketlocal@local.com"
admin_fullname: "bitbucketlocal"

#select correct interface to gather their ips
#baseurl: "http://{{ansible_facts.eth1.ipv4.address}}:7990"
baseurl: "http://{{load_balancer_ip}}"
license: "AAABRg0ODAoPeNp1kF9rwjAUxd/zKQJ72R4ykio+CIXNtgNHtbJWB2Mvt/GqYW0qSSrz2y+2itvAt+T+Ob9z7l2xa2kmHeWCiuGYB+NgRKO4oAEPOIka7UC6OdQYbqE0CivZwto09mlbg6oeZVMT68DuHlMlUVssjnvsxqNsNkveoulzShatkTuwGIPD8KTLBGc8IOeV5HuvzPFXUzAuLuhk5jG32TmaA5ppHE7ExztbFcsXxqMsYfHiNT0b88IQoXZoQmdaJHlbWmnU3qlG9xWP8G0NWt7w0gt5N+qA/crZugen0zhP5iwVIxEMB6MB8b/wbyUzW9DKQkf0WnoNVaORRAa72v+79Lh5W5doss3SorEhu7jIHZhTlg1UFknV+1j5kZN4QGK8hpsoV7byCx29Px2B9ld4+BzT5ABV27HJ9dkn+wGSurDaMCwCFH7Zfd67VV4SApUqjo5FZn5IQHA8AhRvS8VyjAzaKYTzucu6ZkEEZ3kiDQ==X02g8"
displayname: "Local Bitbucket"

postgresql_server : "192.168.30.22"
postgresql_db : "bitbucketdb"
postgresql_user: "bitbucket"
postgresql_pass: "p@ssw0rd"
extra_params: "?ssl=false"
