---
- name: remove domain from resolv.conf 
  lineinfile: 
    dest: /etc/resolv.conf 
    regexp: "^domain" 
    state: absent
    create: yes

- name: remove  {{bamboo_ip}} ip from /etc/hosts 
  lineinfile: 
    dest: /etc/hosts 
    regexp: "^{{bamboo_ip}}" 
    state: absent
    create: yes

- name: remove  {{jira_ip}} ip from /etc/hosts 
  lineinfile: 
    dest: /etc/hosts 
    regexp: "^{{jira_ip}}" 
    state: absent
    create: yes


