---

- name: remove atlbitbucket user
  user:
    name: challenge
    state: absent
    remove: yes

- name: ensure ftp and ftp server is removed
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - ftp
      - vsftpd



